# Generated by Django 5.0.8 on 2024-08-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=70)),
                ('prenom', models.CharField(max_length=70)),
                ('age', models.CharField(max_length=4)),
                ('email', models.CharField(max_length=100)),
                ('option', models.CharField(max_length=50)),
            ],
        ),
    ]
